class ApplicationRecord < ::ActiveRecord::Base
end
module ActionText
end
class ActionText::Record < ::ActiveRecord::Base
end
class ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ActiveStorage::Blob::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
module ActiveStorage
end
class ActiveStorage::Record < ::ActiveRecord::Base
end
class ActiveStorage::VariantRecord::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Role::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Image::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class Poster::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ::ActiveRecord::Relation
end
class ActiveRecord::Relation < ::Object
end
module ActiveRecord::Associations
end
